# Generated by Django 5.2.5 on 2026-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryslot",
            name="weight_charge",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Delivery charge per kg (applied for weight-based pricing)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="deliveryslot",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("EXPRESS", "Express"),
                    ("SAME_DAY", "Same Day"),
                    ("NEXT_DAY", "Next Day"),
                    ("OUT_OF_RADIUS", "2-4 Days Delivery"),
                ],
                max_length=20,
            ),
        ),
    ]
