# Generated by Django 5.2.5 on 2026-05-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="remaining_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="wallet_amount_used",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_slot",
            field=models.CharField(
                choices=[
                    ("EXPRESS", "Express (12 min)"),
                    ("SAME_DAY", "Same Day"),
                    ("NEXT_DAY", "Next Day"),
                ],
                default="EXPRESS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("WALLET", "Wallet Only"),
                    ("WALLET_CARD", "Wallet + Card"),
                    ("WALLET_UPI", "Wallet + UPI"),
                    ("UPI", "UPI"),
                    ("CARD", "Credit/Debit Card"),
                    ("COD", "Cash on Delivery"),
                ],
                default="UPI",
                max_length=20,
            ),
        ),
    ]
