# Generated by Django 5.2.5 on 2026-05-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_chemical_order_order_farmer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_slot",
            field=models.CharField(
                choices=[
                    ("EXPRESS", "Express (12 min)"),
                    ("SAME_DAY", "Same Day"),
                    ("NEXT_DAY", "Next Day"),
                    ("OUT_OF_RADIUS", "2-4 Days Delivery"),
                ],
                default="EXPRESS",
                max_length=20,
            ),
        ),
    ]
