# Generated by Django 5.1.3 on 2026-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="farmerprofile",
            name="fcm_token",
            field=models.TextField(
                blank=True,
                help_text="Firebase Cloud Messaging token for push notifications",
            ),
        ),
        migrations.AddField(
            model_name="farmerprofile",
            name="fcm_token_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
