# Generated by Django 5.2.5 on 2026-05-29 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "emp_id",
                    models.CharField(
                        help_text="Petpooja Employee ID", max_length=50, unique=True
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("PICKER", "Picker"),
                            ("DELIVERY", "Delivery Partner"),
                            ("POS", "POS Operator"),
                            ("ADMIN", "Admin"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this employee is currently active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_date",
                    models.DateField(
                        help_text="The date for which this punch is recorded"
                    ),
                ),
                (
                    "punch_time",
                    models.DateTimeField(help_text="Actual punch timestamp"),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[("In", "In"), ("Out", "Out")],
                        help_text="In or Out punch",
                        max_length=10,
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Raw API response data"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="punches",
                        to="accounts.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-punch_time"],
            },
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["emp_id"], name="accounts_em_emp_id_d84c0e_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "is_active"],
                name="accounts_em_departm_ebe434_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancepunch",
            index=models.Index(
                fields=["employee", "payroll_date"],
                name="accounts_at_employe_f6d4db_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancepunch",
            index=models.Index(
                fields=["payroll_date"], name="accounts_at_payroll_44d061_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancepunch",
            index=models.Index(
                fields=["punch_time"], name="accounts_at_punch_t_8dc72a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancepunch",
            unique_together={("employee", "punch_time", "operation")},
        ),
    ]
