# Generated by Django 5.2.5 on 2026-05-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customer_profile_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAddress",
        ),
    ]
