# Generated by Django 5.2.5 on 2026-05-18 16:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Acceptance"),
                            ("ACCEPTED", "Accepted"),
                            ("PICKED_UP", "Picked Up from Hub"),
                            ("IN_TRANSIT", "In Transit"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("swift", "Swift (12 min)"),
                            ("next-day", "Next Day"),
                            ("standard", "Standard"),
                        ],
                        default="swift",
                        max_length=20,
                    ),
                ),
                (
                    "earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fee_weight",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fee_distance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "fee_premium",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("in_transit_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_assignment",
                        to="orders.order",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "DELIVERY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivery_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryPartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BIKE", "Bike"),
                            ("SCOOTER", "Scooter"),
                            ("CYCLE", "Bicycle"),
                            ("VAN", "Van"),
                        ],
                        default="BIKE",
                        max_length=20,
                    ),
                ),
                ("vehicle_number", models.CharField(blank=True, max_length=20)),
                ("is_online", models.BooleanField(default=False)),
                (
                    "current_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "current_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("total_deliveries", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_partner_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_online", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryStop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("pickup", "Pickup"), ("dropoff", "Dropoff")],
                        max_length=10,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'FreshOn Hub' or 'Customer Home'",
                        max_length=100,
                    ),
                ),
                ("address", models.TextField()),
                ("customer_name", models.CharField(blank=True, max_length=100)),
                (
                    "eta",
                    models.CharField(
                        blank=True, help_text="e.g. '12:45 PM'", max_length=50
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sequence",
                    models.PositiveIntegerField(
                        default=0, help_text="Stop ordering within the mission"
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="delivery_partner.deliveryassignment",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("otp", "OTP Verification"),
                            ("photo", "Delivery Photo"),
                        ],
                        max_length=10,
                    ),
                ),
                ("otp_code", models.CharField(blank=True, max_length=6)),
                ("otp_verified", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="delivery_proofs/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="delivery_partner.deliveryassignment",
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="delivery_partner.deliverystop",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Proofs of Delivery",
                "ordering": ["-created_at"],
            },
        ),
    ]
