# Generated by Django 5.2.5 on 2026-05-21 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery_partner", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryPartnerDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("aadhaar", "Aadhaar Card"),
                            ("pan", "PAN Card"),
                            ("driving_licence", "Driving Licence"),
                            ("vehicle_rc", "Vehicle RC"),
                            ("insurance", "Vehicle Insurance"),
                        ],
                        max_length=20,
                    ),
                ),
                ("doc_number", models.CharField(blank=True, max_length=50)),
                (
                    "file",
                    models.ImageField(
                        blank=True, null=True, upload_to="kyc_documents/%Y/%m/"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "partner",
                    models.ForeignKey(
                        limit_choices_to={"role": "DELIVERY"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "unique_together": {("partner", "doc_type")},
            },
        ),
    ]
