# Generated by Django 5.2.5 on 2026-05-20 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="chemical_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Harmful chemicals reduced in grams per unit",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="farmer_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Farmer support score per unit",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="soil_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Soil supported in sq.ft per unit",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="water_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Water saved/protected in litres per unit",
                max_digits=10,
            ),
        ),
    ]
