# Generated by Django 5.2.5 on 2026-05-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybatch",
            name="purchase_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Price FreshOn pays to the farmer",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inventorybatch",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Selling price to the consumer",
                max_digits=10,
            ),
        ),
    ]
