# Generated by Django 5.2.5 on 2026-05-20 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_product_chemical_score_product_farmer_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="mrp",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="MRP for this variant",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Selling price for this variant",
                max_digits=10,
            ),
        ),
    ]
