# Generated by Django 5.2.13 on 2026-05-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_subcategory_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='unit',
            field=models.CharField(blank=True, help_text='e.g. 500 g, 1 kg, 1 dozen', max_length=50, null=True),
        ),
    ]
