# Generated by Django 5.2.5 on 2026-05-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_productvariant_mrp_productvariant_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorybatch",
            name="mrp",
        ),
        migrations.RemoveField(
            model_name="inventorybatch",
            name="price",
        ),
    ]
