# Generated by Django 5.2.5 on 2026-05-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_remove_inventorybatch_mrp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorybatch",
            name="batch_number",
            field=models.CharField(
                blank=True,
                help_text="Batch number or barcode ID",
                max_length=100,
                null=True,
            ),
        ),
    ]
