# Generated by Django 5.2.5 on 2026-05-21 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventorybatch_batch_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inventorybatch",
            name="batch_number",
        ),
    ]
