# Generated by Django 5.1.3 on 2026-05-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0007_add_batch_approval"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_perishable",
            field=models.BooleanField(
                default=True,
                help_text="Whether this product shows harvest date (e.g., vegetables, fruits) or not (e.g., pots, household items)",
            ),
        ),
    ]
