# Generated by Django 5.1.3 on 2026-05-16 17:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="accumulated_pride_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Total MRP value the user can buy at PRIDE discount",
                max_digits=12,
            ),
        ),
    ]
