# Generated by Django 5.2.5 on 2026-05-16 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Geo-fence radius in meters around the hub",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FreshOn Hub",
                "verbose_name_plural": "FreshOn Hubs",
            },
        ),
        migrations.CreateModel(
            name="PickerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hub_name",
                    models.CharField(blank=True, default="FreshOn Hub", max_length=100),
                ),
                (
                    "hub_latitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=9),
                ),
                (
                    "hub_longitude",
                    models.DecimalField(decimal_places=6, default=0, max_digits=9),
                ),
                (
                    "hub_radius_meters",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Geo-fence radius in meters around the hub",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "pin",
                    models.CharField(
                        blank=True,
                        help_text="Optional numeric PIN for quick login",
                        max_length=6,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub",
                    models.ForeignKey(
                        blank=True,
                        help_text="The hub this picker is primarily assigned to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pickers",
                        to="picker.hub",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickerShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shift_start", models.DateTimeField(auto_now_add=True)),
                ("shift_end", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("total_pick_time_minutes", models.PositiveIntegerField(default=0)),
                ("total_items_picked", models.PositiveIntegerField(default=0)),
                ("total_orders_completed", models.PositiveIntegerField(default=0)),
                ("location_check_points", models.PositiveIntegerField(default=0)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "picker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shift_start"],
            },
        ),
        migrations.CreateModel(
            name="PickerLocationCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="picker.pickershift",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PickerTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("IN_PROGRESS", "In Progress"),
                            ("PACKED", "All Items Packed"),
                            ("HANDED_OVER", "Handed to Delivery"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("urgent", "Urgent"),
                            ("high", "High"),
                            ("normal", "Normal"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "deadline_minutes",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="Minutes from order placement to target dispatch",
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("packed_at", models.DateTimeField(blank=True, null=True)),
                ("handed_over_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "delivery_partner",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "DELIVERY"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picker_task",
                        to="orders.order",
                    ),
                ),
                (
                    "picker",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "PICKER"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="picker_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PickerTaskItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=50)),
                (
                    "batch_code",
                    models.CharField(
                        blank=True, help_text="Expected barcode/QR", max_length=50
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Aisle/shelf location in hub",
                        max_length=100,
                    ),
                ),
                ("emoji", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("packed", "Packed"),
                            ("issue", "Issue"),
                            ("substituted", "Substituted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "scanned_barcode",
                    models.CharField(
                        blank=True,
                        help_text="Actual barcode scanned by picker",
                        max_length=100,
                    ),
                ),
                ("substitution_name", models.CharField(blank=True, max_length=255)),
                ("substitution_sku", models.CharField(blank=True, max_length=50)),
                ("substitution_reason", models.CharField(blank=True, max_length=255)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="picker_task_items",
                        to="orders.orderitem",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="picker.pickertask",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
