# Generated by Django 5.2.5 on 2026-05-07 15:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("picker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hub",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=200,
                        help_text="Geo-fence radius in meters around the hub",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FreshOn Hub",
                "verbose_name_plural": "FreshOn Hubs",
            },
        ),
        migrations.AlterField(
            model_name="pickerprofile",
            name="hub_name",
            field=models.CharField(blank=True, default="FreshOn Hub", max_length=100),
        ),
        migrations.AddField(
            model_name="pickerprofile",
            name="hub",
            field=models.ForeignKey(
                blank=True,
                help_text="The hub this picker is primarily assigned to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pickers",
                to="picker.hub",
            ),
        ),
        migrations.CreateModel(
            name="PickerShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("shift_start", models.DateTimeField(auto_now_add=True)),
                ("shift_end", models.DateTimeField(blank=True, null=True)),
                ("break_start", models.DateTimeField(blank=True, null=True)),
                ("break_end", models.DateTimeField(blank=True, null=True)),
                ("total_pick_time_minutes", models.PositiveIntegerField(default=0)),
                ("total_items_picked", models.PositiveIntegerField(default=0)),
                ("total_orders_completed", models.PositiveIntegerField(default=0)),
                ("location_check_points", models.PositiveIntegerField(default=0)),
                ("device_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "picker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-shift_start"],
            },
        ),
        migrations.CreateModel(
            name="PickerLocationCheckIn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("accuracy", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="picker.pickershift",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
