# Generated by Django 5.2.5 on 2026-05-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_delivery_slot"),
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="icici_bank_rrn",
            field=models.CharField(
                blank=True,
                help_text="Bank Reference Number (RRN) from ICICI",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="icici_merchant_tran_id",
            field=models.CharField(
                blank=True,
                help_text="ICICI Merchant Transaction ID (max 20 chars)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="icici_ref_id",
            field=models.CharField(
                blank=True,
                help_text="ICICI Reference ID from QR generation",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("ICICI", "ICICI"),
                    ("CASH", "Cash"),
                    ("WALLET", "Wallet"),
                    ("OTHER", "Other"),
                ],
                default="RAZORPAY",
                help_text="Payment service provider",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["icici_merchant_tran_id"], name="payment_pay_icici_m_5991d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["razorpay_order_id"], name="payment_pay_razorpa_4e696f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymenttransaction",
            index=models.Index(
                fields=["provider", "status"], name="payment_pay_provide_ceb966_idx"
            ),
        ),
    ]
