# Generated by Django 5.2.5 on 2026-05-16 14:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "gstin",
                    models.CharField(
                        help_text="15-character GSTIN", max_length=15, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "pan",
                    models.CharField(
                        blank=True, help_text="10-character PAN", max_length=10
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Company Profile",
                "verbose_name_plural": "Company Profiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PosInvoiceCounter",
            fields=[
                (
                    "year",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "POS Invoice Counter",
                "verbose_name_plural": "POS Invoice Counters",
            },
        ),
        migrations.CreateModel(
            name="PosSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pride_discount_pct",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.3000"),
                        help_text="PRIDE member discount rate (e.g. 0.30 = 30%)",
                        max_digits=5,
                    ),
                ),
                (
                    "rounding_enabled",
                    models.BooleanField(default=True, help_text="Enable cash rounding"),
                ),
                (
                    "rounding_slab",
                    models.PositiveIntegerField(
                        choices=[(5, "₹5"), (10, "₹10")],
                        default=5,
                        help_text="Round change up to nearest denomination",
                    ),
                ),
                (
                    "max_manual_discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("5.00"),
                        help_text="Maximum manual discount % without manager override",
                        max_digits=5,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "POS Settings",
                "verbose_name_plural": "POS Settings",
            },
        ),
        migrations.CreateModel(
            name="PosCustomer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("Bronze", "Bronze"),
                            ("Silver", "Silver"),
                            ("Gold", "Gold"),
                            ("Platinum", "Platinum"),
                        ],
                        default="Bronze",
                        max_length=20,
                    ),
                ),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "is_pride",
                    models.BooleanField(
                        default=False, help_text="Whether customer is a PRIDE partner"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pos_customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Customer",
                "verbose_name_plural": "POS Customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PosEmployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        help_text="e.g. EMP-001", max_length=20, unique=True
                    ),
                ),
                (
                    "pin",
                    models.CharField(
                        help_text="Numeric PIN for quick terminal login", max_length=6
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_manager",
                    models.BooleanField(
                        default=False, help_text="Can authorize refunds and returns"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pos_employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Employee",
                "verbose_name_plural": "POS Employees",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="PosShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "opening_cash",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "closing_cash",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "cash_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("txn_count", models.PositiveIntegerField(default=0)),
                (
                    "rounding_loss",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total rounding adjustment loss for this shift",
                        max_digits=10,
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="pos.posemployee",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PosTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("SALE", "Sale"), ("RETURN", "Return")],
                        default="SALE",
                        max_length=10,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Sodexo", "Sodexo"),
                            ("Wallet", "Wallet"),
                            ("Split", "Split Payment"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "member_discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "manual_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Manual discount % applied",
                        max_digits=5,
                    ),
                ),
                (
                    "manual_discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Manual discount amount in ₹",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_reason",
                    models.TextField(
                        blank=True, help_text="Reason for manual discount"
                    ),
                ),
                (
                    "surcharge",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "rounding_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Rounding amount added to total (positive = round up)",
                        max_digits=10,
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "receipt_delivery",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Print", "Print"),
                            ("WhatsApp", "WhatsApp"),
                            ("SMS", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="Transaction without customer identification",
                    ),
                ),
                (
                    "is_b2b",
                    models.BooleanField(
                        default=False,
                        help_text="B2B / company purchase with GST invoice",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Sequential tax invoice ID",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="pos.companyprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="pos.poscustomer",
                    ),
                ),
                (
                    "discount_applied_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Employee who authorized the manual discount",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discounted_transactions",
                        to="pos.posemployee",
                    ),
                ),
                (
                    "related_transaction",
                    models.ForeignKey(
                        blank=True,
                        help_text="For RETURN type: links to the original SALE transaction",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="returns",
                        to="pos.postransaction",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="pos.posshift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosTender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("UPI", "UPI"),
                            ("Card", "Card"),
                            ("Sodexo", "Sodexo"),
                            ("Wallet", "Wallet"),
                            ("Split", "Split Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenders",
                        to="pos.postransaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosTransactionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        help_text="Product ID from inventory", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("weighed", models.BooleanField(default=False)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Supports fractional for weighed items",
                        max_digits=8,
                    ),
                ),
                ("member_eligible", models.BooleanField(default=False)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST % at time of sale",
                        max_digits=5,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pos.postransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PosWastageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pid",
                    models.CharField(
                        help_text="Product ID from inventory", max_length=50
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=8)),
                ("weighed", models.BooleanField(default=False)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Spoiled", "Spoiled"),
                            ("Damaged", "Damaged"),
                            ("Expired", "Expired"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wastage_logs",
                        to="pos.posshift",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Wastage Log",
                "verbose_name_plural": "POS Wastage Logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
