# Generated by Django 5.2.5 on 2026-05-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                help_text="Primary contact phone for auto-detection",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="poscustomer",
            name="is_b2b_contact",
            field=models.BooleanField(
                default=False,
                help_text="Whether this customer represents a B2B business",
            ),
        ),
    ]
