# Generated by Django 5.2.5 on 2026-05-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("customer_phone", models.CharField(blank=True, max_length=15)),
                ("customer_email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Late Delivery", "Late Delivery"),
                            ("Damaged Product", "Damaged Product"),
                            ("Payment Issue", "Payment Issue"),
                            ("App Issue", "App Issue"),
                            ("Wrong Item", "Wrong Item Delivered"),
                            ("Refund Request", "Refund Request"),
                            ("Quality Concern", "Quality Concern"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("angry", "Angry"),
                            ("frustrated", "Frustrated"),
                            ("neutral", "Neutral"),
                            ("happy", "Happy"),
                        ],
                        default="neutral",
                        max_length=20,
                    ),
                ),
                (
                    "sentiment_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Sentiment score from -1.0 to 1.0",
                        max_digits=4,
                    ),
                ),
                (
                    "ai_suggested_reply",
                    models.TextField(
                        blank=True, help_text="AI-generated reply suggestion"
                    ),
                ),
                (
                    "related_order",
                    models.CharField(
                        blank=True,
                        help_text="Order tracking ID if applicable",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "sla_minutes",
                    models.PositiveIntegerField(
                        default=120, help_text="SLA time in minutes"
                    ),
                ),
                ("sla_deadline", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Ticket",
                "verbose_name_plural": "Support Tickets",
                "ordering": ["-created_at"],
            },
        ),
    ]
