# Generated by Django 5.1.3 on 2026-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_companyprofile_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postransaction",
            name="pride_limit_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
