# Generated by Django 5.2.5 on 2026-05-26 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0002_supportticket"),
    ]

    operations = [
        migrations.CreateModel(
            name="PosExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Supplies", "Supplies"),
                            ("Maintenance", "Maintenance"),
                            ("Travel", "Travel"),
                            ("Food", "Food"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="pos.posemployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Expense",
                "verbose_name_plural": "POS Expenses",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PosLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="pos.posemployee",
                    ),
                ),
            ],
            options={
                "verbose_name": "POS Leave Request",
                "verbose_name_plural": "POS Leave Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
